default: &default

development:
  <<: *default
  # Geostellar API user and key values (stored in environment variables)
  geo_api_user: <%= ENV["TESTAPP_GEO_API_USER"] %>
  geo_api_key: <%= ENV["TESTAPP_GEO_API_KEY"] %>

test:
  <<: *default

production:
  <<: *default
