# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9302feed01011fcb5d838e7f1b0a9a5f55af899c2a259828807faa94c34e112e0797375a9d8bed88eb258499e690d81300579d4059300870e57282ff63a8337a

test:
  secret_key_base: 73ab82e2927216b397eb8a9f2ba38550e6c583271af7482582f6d73ce4965033400beb1ef20cefe490ad6fda54b72580156f832d25682cc8602a8b18f3de0b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
# disabling this for testing
  secret_key_base: 73ab82e2927216b397eb8a9f2ba38550e6c583271af7482582f6d73ce4965033400beb1ef20cefe490ad6fda54b72580156f832d25682cc8602a8b18f3de0b3
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
